### ISSUE TITLE
Missing entity encoding in generated HTML

### ISSUE THREAD

**Issue by epistemex** [mdn/data#192] opened 2018-03-15 12:14 UTC
Hi, just discovered that there is sometimes a missing entity encoding of for example `>` chars inside the HTML title description.

Example:

1) Go to: view-source:https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

And locate the "Return value" section within the wikiarticle.

2) Inside the "title" value of the A-element there is a `>` that is not encoded properly to `&gt;`.

![exsrc](https://user-images.githubusercontent.com/26116778/37462584-69aa856e-284a-11e8-8d04-949238669287.jpg)

I tried to trace it back to root-cause by entering edit mode. Of course, in edit mode you'll only see a `domxref` tag:

![2018-03-15_06-02-37](https://user-images.githubusercontent.com/26116778/37462276-002f93f0-2817-11e8-9c7f-056b0a1fa724.jpg)

and following the breadcrumbs ended up in nothing I could correct (AFAICS) so this may require change in code base?

**Comment by jwhitlock** [comment] 2018-03-15 21:07
Thanks for the report, the screenshots, and the investigation. This took a bit of work to track down the cause. The source is [kuma](https://travis-ci.org/mozilla/kuma), the wiki engine of MDN. Bugs for Kuma are reported in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=developer.mozilla.org), but I think we can discuss here and file the bug later.

Kuma uses [html5lib](https://github.com/html5lib/html5lib-python) to parse and clean up HTML, and this library  escapes ``<`` as ``&lt;`` by default, but not ``>``.  There's been an open issue (https://github.com/html5lib/html5lib-python/issues/201) since 2015 to allow escaping ``>``, but it got bogged down in discussions around the solution.

It does look strange, but browsers seem to have no issue with it. Does your browser, or some other tool, have problems with it?

**Comment by epistemex** [comment] 2018-03-16 17:02
I realized the included snapshots perhaps contribute to make it look a bit more of an issue than I intended :) There should be no problems if the attribute value is parsed properly (looking at regex people with squinted eyes).

I just wanted to point it out in case if someone bumped into it one day and had a moment. But from the thread you linked to, and that there are likely more pressing issues..

**Comment by jwhitlock** [comment] 2018-03-26 20:45
I'm going to close the issue then, without opening one in Bugzilla. I don't think that we should encourage people to parse HTML with regular expressions, and "fixing" this may just encourage them.

**Closed by jwhitlock** 2018-03-26 20:45 UTC
